version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: self-tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: self_tracker_app
    depends_on:
      - db
    env_file:
      - .env
    command: ["python", "src/main.py"]

volumes:
  postgres_data:
