version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: self-tracker
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: self_tracker_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: self-tracker
      DB_USER: postgres
      DB_PASSWORD: "1234"
      DB_PORT: 5432
    command: ["python", "main.py"]

volumes:
  postgres_data:
